# Changes here will be overwritten by Copier
_commit: 0.6.0-30-g6ad1486
_src_path: https://github.com/NLeSC/python-template
copyright_holder: dfvfv
email: sdhg@afvs.afs
full_name: dfv
github_organization: sefwv
keywords: qwe
license: Apachev2
package_name: sdv
package_short_description: sfvdv
template_profile: minimum
version: 0.1.0
